<a href="https://colab.research.google.com/github/swaleha/Python/blob/master/Swaleha_Quiz_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

General Instructions:
- By array, I mean numpy array
- By matrix, I mean a numpy array of 2 dimensions

### 1
Write a function to create and return an integer array of shape (5, 2) from a range between 100 to 200 (including 100, excluding 200) such that the difference between consecutive elements is 10.

In [0]:
def create_integer_array():
  '''
  Input(s):
   None

  Output(s):
   res is the array elements in range between 100 and 200 with consecutive elements that differ by 10 and res array is in shape (5,2)
  '''
  res = np.arange(100, 200, 10, dtype = int)
  return res.reshape(5,2)


### 2
Given a numpy array ```a```, of shape ```(m, n)``` m>=3, n>=3. Write a function to return an array consisting of the elements in 3rd column of ```a``` <br>
Eg., Suppose
``` 
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]    
```
Then 
```
column_3(a) -> [3 6 9]
```

In [0]:
def column_3(a):
 '''
 Input(s):
  a is the array of elements having shape (m, n) such that m >= 3 and n >= 3

 Output(s):
  res is the array elements from 3rd column of array a
 '''

 return a[:, 2]


### 3
Write a function which does the following. Given a numpy array $a$ of shape (m, n), index $i$ and an array $b$ of shape (m, ). Replace the $i_{th}$ column of $a$ with the array $b$  
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]
b = [30, 60, 90]

```    
Then,
```
replace_col(a, 2, b) -> [[1 2 30]
                         [4 5 60]
                         [7 8 90]]
```

In [0]:
def replace_col(a, i, b):
  '''
  Input(s):
   a is the array of elements of shape (m, n)
   i is the column index 
   b is the second array of shape (m,)

  Output(s):
   a is the array elements in which column of index i in array a is replaced by array b
  '''
  a[:, i] = b
  return a

print(replace_col(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), 2, np.array([30, 60, 90])))

[[ 1  2 30]
 [ 4  5 60]
 [ 7  8 90]]


### 4
Write a function which does the following. Given a numpy array $a$ of shape (m, n) and indices $i$, $j$. Return a numpy array which swaps the columns $i$ and $j$ of $a$
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]

swap_cols(a, 0, 2) -> [[3 2 1]
                       [6 5 4]
                       [9 8 7]]
```

In [0]:
def swap_cols(a, i, j):
 '''
 Input(s):
  a is the array of elements of shape (m, n)
  i and j are the column indices
  
 Output(s):
  a is the array elements in which elements in column i are swapped with the elements in column j
 '''
 a[:,[i, j]] = a[:, [j, i]]

 return a


[[3 2 1]
 [6 5 4]
 [9 8 7]]


## 5

There are various equivalent ways to define the determinant of a square matrix A, i.e. one with the same number of rows and columns. Perhaps the simplest way to express the determinant is by considering the elements in the top row and the respective minors; starting at the left, multiply the element by the minor, then subtract the product of the next element and its minor, and alternate adding and subtracting such products until all elements in the top row have been exhausted. For example, here is the result for a 4 × 4 matrix: <br>

<img src = "https://drive.google.com/uc?id=1TTljfFZAnOvqgAOiOrv6r4DDRROD-Vph"> <br>

Also, for a 2x2 matrix, this is the formula - <br>
<img src = "https://drive.google.com/uc?id=1H3aFpr1guevWjz4F-XRUQ9eP5TfjVLwu"> <br>

###5.1 Minor
Write a function that does the following. 
Given a square matrix $A$ and an index $i$, find and return the sub-matrix that is the minor corresponding to element at index $i$ of the first row of $A$

In [0]:
def minor(A, i):
  '''
  Input(s):
     A is the array of elements of a square matrix
     i is the column index
  
  Output(s):
     minor_matrix is the sub-matrix of A which contains minor of elements at index i of first row in A
  '''

  minor_matrix = np.hstack([A[1:, :i], A[1: , i+1:]])

  return minor_matrix

###5.2
Given a square matrix $A$, write a function that computes and return the determinant using the formula given above and the helper function that you have defined called ```minor```. <br>
(Do not use the functions to compute determinant which numpy provides built in)

In [0]:
def determinant(A):

    if(A.shape[0] == 2):

        return((A[0, 0] * A[1, 1]) - (A[0, 1] * A[1, 0]))
    
    else:

      determinant_A = 0

      for i in range(A.shape[0]):

        determinant_A += (-1)**(i) * A[0, i] * determinant(minor(A, i))

    return determinant_A
