<a href="https://colab.research.google.com/github/swaleha/Python/blob/master/Swaleha_Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numerical Operations on Numpy

In [0]:
import numpy as np

In [0]:
# Basic Scalar Operations
a = np.array([1, 3, 8, 9])
a + 1

array([ 2,  4,  9, 10])

In [0]:
# Matrix Multiplications
c = np.diag([1, 3, 4, 5])
print(c * c)
print()
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  9  0  0]
 [ 0  0 16  0]
 [ 0  0  0 25]]

[[ 1  0  0  0]
 [ 0  9  0  0]
 [ 0  0 16  0]
 [ 0  0  0 25]]


In [0]:
# Comparison
a = np.array([1, 2, 4, 3])
b = np.array([1, 4, 2, 3])
print(a == b)
print(np.array_equal(a, b))


[ True False False  True]
False


In [0]:
# Logical Operations
a = np.array([1, 1, 0, 0], dtype = 'bool')
b = np.array([1, 0, 1, 0], dtype = 'bool')

print(np.logical_or(a, b))

[ True  True  True False]


In [0]:
# Transcendental Functions
a = np.arange(1, 4)
print(a)
print(np.exp(a))
print(np.log(a))
print(np.sin(a))

[1 2 3]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


In [0]:
a# Computing Sum
a = np.array([2, 3, 4])
print(np.sum(a))

x = np.array([[1, 2], [3, 4]])
print(np.sum(x, axis = 0))# Sum along column
print(np.sum(x, axis = 1)) # Sum along rows

9
[4 6]
[3 7]


In [0]:
# Identifying minimum and maximum element of an array
a = np.array([1, 99, 0, 67, 688, 7])
print(a.min())# min/max value and its index value
print(a.max())
print(a.argmin())
print(a.argmax())


0
688
2
4


In [0]:
# Logical operations
x = np.zeros((3, 3))
print(np.all(x == 0))
print(np.any(x != 0))

True
False


In [0]:
a = np.array([1, 4, 3])
b = np.array([2, 3, 4])
print(a<=b)
print((a<=b).all())

[ True False  True]
False


In [0]:
# Statistics
x = np.array([2, 1, 3, 0])
print(x.mean())# mean
print(np.median(x)) # median
print(np.var(x))
print(x.std())# standard deviation

y = np.array([[1, 2, 3], [4, 5, 7]])
print(y)
print(np.median(y, axis = 0))

1.5
1.5
1.25
1.118033988749895
[[1 2 3]
 [4 5 7]]
[2.5 3.5 5. ]


In [0]:
# Flattening
a = np.array([[1, 2, 4], [4, 5, 6]])
print("Flattening a matrix: \n", np.ravel(a))
print("Transpose of a matirx: \n", a.T)
print("Flattening transpose of a matrix: \n", a.T.ravel())

Flattening a matrix: 
 [1 2 4 4 5 6]
Transpose of a matirx: 
 [[1 4]
 [2 5]
 [4 6]]
Flattening transpose of a matrix: 
 [1 4 2 5 4 6]


In [0]:
# Reshaping
print(a)
b = np.ravel(a)
print(b)
c = b.reshape((3, 2))
print(c)


[[1 2 4]
 [4 5 6]]
[1 2 4 4 5 6]
[[1 2]
 [4 4]
 [5 6]]


In [0]:
# Sorting Data
a = np.array([[5, 4], [8, 6]])
print("Unsorted array: \n", a)
b = np.sort(a, axis = 1)
print("\nRow wise sort: \n", b)
print("\nThe array of indices of an unsorted array")
c = np.argsort(a)
print('c\n', c)

print("\nThe array of indices of a sorted array: \n")
e = np.argsort(b)
print('e\n', e)

Unsorted array: 
 [[5 4]
 [8 6]]

Row wise sort: 
 [[4 5]
 [6 8]]

The array of indices of an unsorted array
c
 [[1 0]
 [1 0]]

The array of indices of a sorted array: 

e
 [[0 1]
 [0 1]]


In [0]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
print(x)
print(x.ndim)
print(np.shape(x))




[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
3
(2, 3, 1)


In [0]:
labels=np.array([1,3,5])

print(labels)

print(labels[:, None])


[1 3 5]
[[1]
 [3]
 [5]]


In [0]:
import numpy as np
x = np.arange(9).reshape((3, 3))
print(x)
np.random.shuffle(x)
x


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [0]:
def match(a, b):
  '''
  Inputs:
   a and b are arrays of 1 dimension
  Outputs:
   array of indices which has indices of matching elements from arrays a and b
  '''

  match_list = []
  
  for i in range(a.shape[0]):
    if(a[i] == b[i]):
      match_list = match_list + [i]

  return match_list

print(match(np.array([1,2,3,2,3,4,3,4,5,6]), np.array([7,2,10,2,7,4,9,4,9,8])))

[1, 3, 5, 7]
